// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass AIViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        AIViewModel(Microsoft.Terminal.Settings.Model.AISettings aiSettings);

        Int32 MaxContextBlocks;
        String CopilotCliPath;

        Boolean IsCopilotCliDetected { get; };
        Boolean IsCopilotAuthLoggedIn { get; };

        // Device code flow
        String UserCode { get; };
        String VerificationUri { get; };
        Boolean IsOAuthInProgress { get; };
        String OAuthError { get; };

        void CopilotAuthLogin();
        void OpenVerificationUri();
        void CopyUserCode();
        void CancelOAuth();
        void Disconnect();
    }
}
