// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "IPaneContent.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass AIPaneContent : Windows.UI.Xaml.Controls.UserControl,
                                                     IPaneContent,
                                                     Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        AIPaneContent();
        void SetLastActiveControl(Microsoft.Terminal.Control.TermControl control);

        String StatusText { get; };
        Boolean IsStreaming { get; };

        event Windows.Foundation.TypedEventHandler<Object, Microsoft.Terminal.Settings.Model.ActionAndArgs> DispatchActionRequested;
    }
}
